/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jtsh;

import java.lang.System;
import java.util.Scanner;
import java.nio.file.Paths;

public class App {
    String getUserName() {
        return System.getProperty("user.name");
    }

    String getUserHome() {
        return System.getProperty("user.home");
    }

    String getCwd() {
        return Paths.get("").toAbsolutePath().toString();
    }

    String getPrompt() {
        return getCwd().replace(getUserHome(), "~");
    }

    public static void main(String[] args) {
        App app = new App();
        System.out.println("Hello " + app.getUserName());
        System.out.println("user home: " + app.getUserHome());

        String userHome = app.getUserHome();

        try (Scanner scanner = new Scanner(System.in)) {
            while (true) {
                String prompt = app.getPrompt();
                System.out.print(prompt + "> ");
                String line = scanner.nextLine();

                if (line.equals("exit")) {
                    break;
                }
                if (line.equals("")) {
                    continue;
                }
                var cmdList = line.split(" ");
                CommandExecutor.execute(cmdList);
            }
        }


    }
}
