/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javadev;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.lang.System;
import java.util.Scanner;
import java.nio.file.Paths;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public String getUserName() {
        return System.getProperty("user.name");
    }

    public String getCwd() {
        return Paths.get("").toAbsolutePath().toString();
    }

    public void execCmd(String cmd) {
        try {
            Process proc = Runtime.getRuntime().exec(cmd);
            InputStream stream = proc.getInputStream();
            BufferedReader br = new BufferedReader(new InputStreamReader(stream));
            String line = null;
            while ((line = br.readLine()) != null) {
                System.out.println(line);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        App app = new App();
        System.out.println("Hello " + app.getUserName());

        Scanner scanner = new Scanner(System.in);
        while (true) {
            String cwd = app.getCwd();
            System.out.print(cwd + "> ");
            String line = scanner.nextLine();
            app.execCmd(line);
        }
    }
}
