/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javadev;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public String getHelloText(String name) {
        return "Hello " + name;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().getHelloText("zztkm"));
    }
}
